name: Update Python dependencies
on:
  pull_request:
    paths:
      - '.github/workflows/pdm-update.yml'
  schedule:
    - cron: "25 0 * * *"
  workflow_dispatch:
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update dependencies
        uses: pdm-project/update-deps-action@v1.11
        with:
          commit-message: "chore: Update pdm.lock"
          pr-title: ":seedling:: update Python dependencies"
