name: Update Python dependencies
on:
  pull_request:
    paths:
      - '.github/workflows/pdm-update.yml'
  schedule:
    - cron: "25 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Update dependencies
        uses: astral-sh/setup-uv@v5
        with:
          token: ${{ secrets.GH_UPDATE_TOKEN }}
          commit-message: "chore: Update uv.lock"
          pr-title: ":seedling: Update Python dependencies"
