name: Run Linters
on:
  push:
  pull_request:
    branches: [main]
jobs:
  run_linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-python@v5.5.0
      - name: Run linters
        run: make tox
